module.exports.ruas = "http://localhost:7776/ruas/"
module.exports.rua  = "http://localhost:7776/rua/"
module.exports.ruaoriginal  = "http://localhost:7776/rua/original/"
module.exports.ruaFields  = "http://localhost:7776/rua/fields/"
module.exports.ruaFiguras  = "http://localhost:7776/rua/figures/"
module.exports.entidades = "http://localhost:7776/entidades/"
module.exports.entidadenome = "http://localhost:7776/entidadenomes/"
module.exports.userlogin = "http://localhost:7775/users/login"
module.exports.userregister = "http://localhost:7775/users/register"
module.exports.verifytoken = "http://localhost:7775/users/verifytoken"

